=== szabolcs4444/DO425GxmlGyak/XMLFeladatDO425G/DOMParseDO425G/XMLSchemaDO425G.xsd
<?xml version="1.0" encoding="UTF-8"?>


 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:complexType name="nevTipus">
        <xs:sequence>
            <xs:element name="vendegnev" type="xs:string"/>
            
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DolgozikTipus">
        <xs:sequence>
            <xs:element name="idotartam">
            	<xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="4"/>
                        <xs:maxInclusive value="12"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="ref_szigsz" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{6}[A-Z]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="ref_szalloda" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{8}-[0-9]{1}-[0-9]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="VegzettsegTipus">
        <xs:sequence>
            <xs:element name="vegzettseg" type="xs:string"/>
            
        </xs:sequence>
        <xs:attribute name="ref_szigsz" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{6}[A-Z]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="irsz">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1000"/>
                        <xs:maxInclusive value="9999"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="telepules" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hsz">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="SzuletesTipus">
        <xs:sequence>
            <xs:element name="ido">
                <xs:simpleType>
                    <xs:restriction base="xs:date">
                    <xs:pattern value="([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="hely" type="xs:string"/>
            
            
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="telefonszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9]{1}[0-9]{8}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="arTipus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="korTipus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="15"/>
            <xs:maxInclusive value="110"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="meretTipus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="15"/>
            <xs:maxInclusive value="200"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="SzallodaTipus" mixed="true">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="cim" type="cimTipus"/>
            <xs:element name="telefonszam" type="telefonszamTipus"/>

        </xs:sequence>
        <xs:attribute name="szalloda_adoszam" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{8}-[0-9]{1}-[0-9]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="ref_szoba" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minExclusive value="0"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="ref_vendeg" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{6}[A-Z]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="ref_alkalmazott" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{6}[A-Z]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="VendegTipus" mixed="true">
        <xs:sequence>
            <xs:element name="nev" type="nevTipus"/>
            <xs:element name="cim" type="cimTipus"/>
            <xs:element name="telefonszam" type="telefonszamTipus"/>
        </xs:sequence>
        <xs:attribute name="vendeg_szigsz" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{6}[A-Z]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="ref_szalloda" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{8}-[0-9]{1}-[0-9]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="AlkalmazottTipus" mixed="true">
        <xs:sequence>
            <xs:element name ="kor" type="korTipus"/>
            <xs:element name="szuletesi_datum" type="SzuletesTipus"/>
        </xs:sequence>
        <xs:attribute name="alkalmazott_szigsz" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{6}[A-Z]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="ref_szalloda" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{8}-[0-9]{1}-[0-9]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="SzobaTipus" mixed="true">
        <xs:sequence>
            <xs:element name="meret" type="meretTipus"/>
            <xs:element name="ar" type="arTipus"/>
            <xs:element name ="tipus" type="xs:string"></xs:element>
        </xs:sequence>
        <xs:attribute name="szoba_ajtoszam" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minExclusive value="0"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="ref_szalloda" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{8}-[0-9]{1}-[0-9]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:element name="Szallodak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="szalloda" type="SzallodaTipus" maxOccurs="unbounded"/>
                <xs:element name="szoba" type="SzobaTipus" maxOccurs="unbounded"/>
                <xs:element name="vendeg" type="VendegTipus" maxOccurs="unbounded"/>
                <xs:element name="alkalmazott" type="AlkalmazottTipus" maxOccurs="unbounded"/>
                <xs:element name="vegzettsegek" type = "VegzettsegTipus" maxOccurs="unbounded"/>
                <xs:element name="dolgozik" type = "DolgozikTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="szallodaKey">
            <xs:selector xpath="szalloda"/>
            <xs:field xpath="@szalloda_adoszam"/>
        </xs:key>
        <xs:key name="szobaKey">
            <xs:selector xpath="szoba"/>
            <xs:field xpath="@szoba_ajtoszam"/>
        </xs:key>
        <xs:key name="vendegKey">
            <xs:selector xpath="vendeg"/>
            <xs:field xpath="@vendeg_szigsz"/>
        </xs:key>
        
        <xs:key name="alkalmazottKey">
            <xs:selector xpath="alkalmazott"/>
            <xs:field xpath="@alkalmazott_szigsz"/>
        </xs:key>
        
        <xs:keyref refer="vendegKey" name="refVendeg_sz">
            <xs:selector xpath="./szalloda"></xs:selector>
            <xs:field xpath="@ref_vendeg"></xs:field>
        </xs:keyref>
        
        <xs:keyref refer="alkalmazottKey" name="refAlkalmazott_sz">
            <xs:selector xpath="./szalloda"></xs:selector>
            <xs:field xpath="@ref_alkalmazott"></xs:field>
        </xs:keyref>
        

        <xs:keyref refer="szobaKey" name="refSzalloda">
            <xs:selector xpath="./szalloda"/>
            <xs:field xpath="@ref_szoba"/>
        </xs:keyref>

        <xs:keyref refer="szallodaKey" name="refSzoba">
            <xs:selector xpath="./szoba"/>
            <xs:field xpath="@ref_szalloda"/>
        </xs:keyref>
        <xs:keyref refer="szallodaKey" name="refVendeg">
            <xs:selector xpath="./vendeg"/>
            <xs:field xpath="@ref_szalloda"/>
        </xs:keyref>
        <xs:keyref refer="szallodaKey" name="refAlkalmazott">
            <xs:selector xpath="./alkalmazott"/>
            <xs:field xpath="@ref_szalloda"/>
        </xs:keyref>
        <xs:keyref refer="szallodaKey" name="refDolgozik">
            <xs:selector xpath="./dolgozik"/>
            <xs:field xpath="@ref_szalloda"/>
        </xs:keyref>
        
        <xs:keyref refer="alkalmazottKey" name="refVegzettsegek_sz">
            <xs:selector xpath="./vegzettsegek"></xs:selector>
            <xs:field xpath="@ref_alkalmazott"></xs:field>
        </xs:keyref>
        <xs:keyref refer="alkalmazottKey" name="refDolgozik_sz">
            <xs:selector xpath="./dolgozik"></xs:selector>
            <xs:field xpath="@ref_alkalmazott"></xs:field>
        </xs:keyref>
        
    </xs:element>


</xs:schema>

=== szabolcs4444/DO425GxmlGyak/XMLFeladatDO425G/DOMParseDO425G/XMLDO425G.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Szallodak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaDO425G.xsd">
	<szalloda ref_alkalmazott="135792CA" ref_szoba="100" ref_vendeg="123456AB" szalloda_adoszam="12345678-2-25">
	    <nev>Teszt 1</nev>
		<cim>
			<irsz>3700</irsz>
			<telepules>Kazincbarcika</telepules>
			<utca>Építők utca</utca>
			<hsz>44</hsz>
		</cim>
	<telefonszam>302345678</telefonszam>
	</szalloda>

	<szalloda ref_alkalmazott="246819MA" ref_szoba="101" ref_vendeg="123456AB" szalloda_adoszam="87654321-2-25">
		<nev>Teszt 2</nev>
		<cim>
			<irsz>3519</irsz>
			<telepules>Miskolc</telepules>
			<utca>Teszt utca</utca>
			<hsz>69</hsz>
		</cim>
		<telefonszam>202345678</telefonszam>
	</szalloda>

	<szalloda ref_alkalmazott="147259GB" ref_szoba="102" ref_vendeg="245246AB" szalloda_adoszam="54654754-2-25">
		<nev>Teszt 3</nev>
		<cim>
			<irsz>4400</irsz>
			<telepules>Nyíregyháza</telepules>
			<utca>Dísz tér</utca>
			<hsz>48</hsz>
		</cim>
		<telefonszam>702345678</telefonszam>
	</szalloda>

	<szoba ref_szalloda="12345678-2-25" szoba_ajtoszam="101">
		<meret>42</meret>
		<ar>31500</ar>
		<tipus>superior</tipus>
	</szoba>

	<szoba ref_szalloda="12345678-2-25" szoba_ajtoszam="100">
		<meret>18</meret>
		<ar>15000</ar>
		<tipus>stantard</tipus>
	</szoba>

	<szoba ref_szalloda="12345678-2-25" szoba_ajtoszam="102">
		<meret>18</meret>
		<ar>15000</ar>
		<tipus>duplex</tipus>
	</szoba>


	<vendeg ref_szalloda="54654754-2-25" vendeg_szigsz="245246AB">
		<nev>
			<vendegnev>Nagy Tibor</vendegnev>
		</nev>
		<cim>
			<irsz>3519</irsz>
			<telepules>Miskolc</telepules>
			<utca>Vadgalamb utca</utca>
			<hsz>21</hsz>
		</cim>
		<telefonszam>309856543</telefonszam>
	</vendeg>

	<vendeg ref_szalloda="12345678-2-25" vendeg_szigsz="123456AB">
		<nev>

			<vendegnev>Kiss Pista</vendegnev>
		</nev>
		<cim>
			<irsz>3515</irsz>
			<telepules>Miskolc</telepules>
			<utca>Egyetem</utca>
			<hsz>1</hsz>
		</cim>
		<telefonszam>309876543</telefonszam>
	</vendeg>

	<vendeg ref_szalloda="12345678-2-25" vendeg_szigsz="654321AB">
		<nev>
			<vendegnev>Tóth Aladár</vendegnev>
		</nev>

		<cim>
			<irsz>8000</irsz>
			<telepules>Székesfehérvár</telepules>
			<utca>Erdő utca</utca>
			<hsz>140</hsz>
		</cim>
		<telefonszam>209876543</telefonszam>
	</vendeg>

	<alkalmazott alkalmazott_szigsz="135792CA" ref_szalloda="12345678-2-25">
		<kor>23</kor>
		<szuletesi_datum>
			<ido>1997-02-12</ido>
			<hely>Kazincbarcika</hely>
		</szuletesi_datum>



	</alkalmazott>
	<alkalmazott alkalmazott_szigsz="246819MA" ref_szalloda="87654321-2-25">
		<kor>38</kor>
		<szuletesi_datum>
			<ido>1982-12-12</ido>
			<hely>Miskolc</hely>
		</szuletesi_datum>



	</alkalmazott>

	<alkalmazott alkalmazott_szigsz="147259GB" ref_szalloda="54654754-2-25">
		<kor>41</kor>
		<szuletesi_datum>
			<ido>1980-05-05</ido>
			<hely>Győr</hely>
		</szuletesi_datum>



	</alkalmazott>

	<vegzettsegek ref_szigsz="147259GB">
		<vegzettseg>Erettsegi</vegzettseg>
	</vegzettsegek>

	<vegzettsegek ref_szigsz="246819MA">
		<vegzettseg>Szakmunkás</vegzettseg>
	</vegzettsegek>

	<vegzettsegek ref_szigsz="135792CA">
	    <vegzettseg>Egyetem</vegzettseg>
	</vegzettsegek>

	<dolgozik ref_szalloda="12345678-2-25" ref_szigsz="147259GB">
	 <idotartam>8</idotartam>
	</dolgozik>

	<dolgozik ref_szalloda="87654321-2-25" ref_szigsz="246819MA">
		<idotartam>6</idotartam>
	</dolgozik>

	<dolgozik ref_szalloda="54654754-2-25" ref_szigsz="135792CA">
		<idotartam>12</idotartam>
	</dolgozik>
</Szallodak>
