=== szabolcs4444/DO425GxmlGyak/DO425G_1015/ERkonvSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<xs:element name="ER">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Entity" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="name" type="xs:string" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" />
									<xs:attribute name="value" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" />
					</xs:complexType>
				</xs:element>
				<xs:element name="relation" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="name" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="member" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="name" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="cardinatlity" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="card" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="name" type="xs:string" />
														<xs:attribute name="value" type="xs:string" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== szabolcs4444/DO425GxmlGyak/DO425G_1015/ERkonv.xml
<?xml version="1.0" encoding="UTF-8"?>
<ER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ERkonvSchema.xsd">
	<Entity name="A">
		<attribute name="a" value="primaryKey" />
		<attribute name="b" value="multivalued">
			<attribute name="x" />
			<attribute name="y" />
		</attribute>
		<attribute name="c" value="composit">
			<attribute name="" />
			<attribute name="" />
		</attribute>
	</Entity>
	<Entity name="B">
		<attribute name="a" value="primaryKey" />
		<attribute name="b" value="composit">
			<attribute name="x" />
			<attribute name="y" />
		</attribute>
	</Entity>
	<Entity name="C">
		<attribute name="a" value="primaryKey" />
		<attribute name="b" />
	</Entity>
	<relation>
		<attribute name="c" />
		<member name="A" />
		<member name="B" />
		<cardinatlity>
			<card name="a" value="many" />
			<card name="b" value="many" />
		</cardinatlity>
	</relation>

	<relation>
		<member name="B" />
		<member name="C" />
		<cardinatlity>
			<card name="b" value="many" />
			<card name="c" value="one" />
		</cardinatlity>

	</relation>
</ER>
