=== szabolcs4444/DO425GxmlGyak/DO425G_1008/nevjegykartya.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="nevjegykartyak">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nevjegykartya">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nev" type="xs:string" />
							<xs:element name="ceg">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="cim">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="iranyitoszam"
														type="xs:positiveInteger" />
													<xs:element name="varos" type="xs:string" />
													<xs:element name="utca" type="xs:string" />
													<xs:element name="hazszam"
														type="xs:positiveInteger" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="nev" type="xs:string" />
										<xs:element name="telefonszam">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:positiveInteger">
														<xs:attribute default="46" name="korzet" type="xs:string" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="weblap" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>

							<xs:element name="beosztas" type="xs:string" />
							<xs:element name="telefonszam">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:positiveInteger">
											<xs:attribute default="46" name="korzet" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="email" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="id" type="xs:ID" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== szabolcs4444/DO425GxmlGyak/DO425G_1008/nevjegykartya.xml
<?xml version="1.0" encoding="UTF-8"?>
<nevjegykartyak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="nevjegykartya.xsd">
	<nevjegykartya id="n1">
		<nev>Virág Szabolcs</nev>
		<ceg>
			<cim>
				<iranyitoszam>6700</iranyitoszam>
				<varos>Szeged</varos>
				<utca>Fő </utca>
				<hazszam>11</hazszam>
			</cim>
			<nev>Virág József</nev>
			<telefonszam korzet="36">303973853</telefonszam>
			<weblap>www.cegvezeto.hu</weblap>
		</ceg>
		<beosztas>Boss</beosztas>
		<telefonszam korzet="36">305963355</telefonszam>
		<email>vezeto@gmail.com</email>
	</nevjegykartya>
</nevjegykartyak>
