=== szabolcs4444/DO425GxmlGyak/DO425G_0924/adatbazis.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE adatbazis [
<!ELEMENT adatbazis (dolgozo+) >
<!ELEMENT dolgozo (kod, nev, fizetes)>
<!ELEMENT kod (#PCDATA) >
<!ATTLIST dolgozo id ID #REQUIRED >
<!ELEMENT nev (#PCDATA) >
<!ELEMENT fizetes (#PCDATA) >
]>

=== szabolcs4444/DO425GxmlGyak/gyak3/adatbazis.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE adatbazis SYSTEM "adatbazis.dtd" >
<adatbazis>
<dolgozo id="T1">
<kod>K1</kod>
<nev>Tóth Lajos</nev>
<fizetes>15000</fizetes>

</dolgozo>
<dolgozo id="T2">
<kod>K2</kod>
<nev>Molnár István</nev>
<fizetes>15000</fizetes>

</dolgozo>

</adatbazis>
