=== szabolcs4444/DO425GxmlGyak/DO425G_0924/iskola.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iskola [
<!ELEMENT iskola (tanar+, tantargy+)>
<!ELEMENT tanar (nev,szak)>
<!ATTLIST tanar id ID #REQUIRED>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ELEMENT tantargy (tnev,osztaly)>
<!ATTLIST tantargy kod ID #REQUIRED>
<!ATTLIST tantargy oktato IDREF #IMPLIED>
<!ELEMENT tnev (#PCDATA)>
<!ELEMENT osztaly (#PCDATA)>
]>

=== szabolcs4444/DO425GxmlGyak/gyak3/iskola.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE iskola SYSTEM "iskola.dtd" >
<iskola>

<tanar id = "T1">
<nev>Horvát Béla</nev>
<szak>Matematika</szak>
</tanar>
<tanar id = "T2">
<nev> Lakatos Ferenc</nev>
<szak>Technika</szak>

</tanar>

<tantargy kod ="O1" oktato="T1">
<tnev>Lineáris Algebra</tnev>
<osztaly>8C</osztaly>
</tantargy>

</iskola>
